" Enabling pathogen
execute pathogen#infect()

" Disables vi compatibility
set nocompatible

" Enables highlighting
syntax on

" Disable modelines
set modelines=0

" Identation
filetype plugin indent on
set tabstop=4      " number of visual spaces per TAB
set softtabstop=4  " number of spaces in tab when editing
set expandtab      " tabs are spaces

" Set line numbers
set number
"set relativenumber
highlight LineNr term=bold cterm=NONE ctermfg=DarkGrey ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE

" Show cursor line
" set cursorline

" Show file stats
set ruler

" Encoding
set encoding=utf-8

" Rendering
set ttyfast

" Brackets highlight
set showmatch

" NERDTree
nnoremap <C-\> :NERDTreeToggle<CR>

" NERDTree shows hidden files
let NERDTreeShowHidden=1

